### ISSUE TITLE
\parencite instead of \cite

### ISSUE THREAD

**Issue by primal-buddhist** [mo-seph/obsidian-copy-as-latex#6]
Hi - latex and obsidian noob here but I have a successful overleaf template that creates Harvard style referencing using \parencite which creates the (Author Year) very nicely. Your plugin uses \cite which seems to render without the parenthesis regardless of what I do. Would it be possible to configure the exact Latex being used somewhere in the plugin?

**Comment by d12bb** [comment]
Instead of `\parencite{}`, I think `\autocite{}` should be used, which decides how to render the citation based on what style (csl) is used. So for styles like Havard or APA it would be parentheses, for other styles footnotes etc.

Related to my issue #4.

**Comment by mo-seph** [comment]
Thanks! fixed in new version - choice of parencite, autocite or basic cite commands in plugin settings
