### ISSUE TITLE
Page numbers in citations

### ISSUE THREAD

**Issue by primal-buddhist** [mo-seph/obsidian-copy-as-latex#7]
When storing a quote in Obsidian I am also storing the page number, just as text next the @link. This is then outside the citation when copied using the plugin to generate latex. 

How can I store the page (or chap) number such that it is in [ ] before the { } in the latex generated.  

I think this is related to the pandoc discussion elsewhere ... ?

**Comment by mo-seph** [comment]
Covers the same ground as Issue #4 - lets keep discussion there.
